var BG = "#0a0e14", BGP = "#121821", BGD = "#060a0f";
var BD = "#1f2937", BDH = "#334155";
var TX = "#e2e8f0", TXD = "#64748b", TXM = "#94a3b8";
var AC = "#f59e0b", ACD = "#92400e";
var GR = "#10b981", RD = "#ef4444";
var FM = '"JetBrains Mono", monospace', FD = '"Space Grotesk", system-ui, sans-serif';

export var styles = {
  app: { minHeight: "100vh", background: BG, color: TX, fontFamily: FD, position: "relative", paddingBottom: 40 },
  grain: { position: "fixed", inset: 0, pointerEvents: "none", background: "radial-gradient(ellipse at top, rgba(245,158,11,0.04) 0%, transparent 60%)", zIndex: 0 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 32px", borderBottom: "1px solid " + BD, position: "relative", zIndex: 1 },
  headerLeft: { display: "flex", alignItems: "center", gap: 16 },
  logo: { fontSize: 32, color: AC },
  brand: { fontSize: 20, fontWeight: 700, letterSpacing: "-0.02em" },
  subBrand: { fontSize: 11, color: TXD, fontFamily: FM, textTransform: "uppercase", letterSpacing: "0.1em", marginTop: 2 },
  headerRight: { display: "flex", gap: 4 },
  tab: { background: "transparent", border: "1px solid " + BD, color: TXM, padding: "8px 16px", fontSize: 11, fontFamily: FM, letterSpacing: "0.1em", cursor: "pointer", borderRadius: 2 },
  tabActive: { background: AC, border: "1px solid " + AC, color: BG, padding: "8px 16px", fontSize: 11, fontFamily: FM, letterSpacing: "0.1em", cursor: "pointer", borderRadius: 2, fontWeight: 700 },
  main: { display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1.2fr)", gap: 24, padding: "24px 32px", position: "relative", zIndex: 1 },
  mainConfig: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 24, padding: "24px 32px", position: "relative", zIndex: 1 },
  col: { display: "flex", flexDirection: "column", gap: 16 },
  panel: { background: BGP, border: "1px solid " + BD, padding: 20, borderRadius: 4 },
  pHead: { display: "flex", alignItems: "baseline", gap: 12, marginBottom: 14 },
  pNum: { fontFamily: FM, fontSize: 11, color: AC, letterSpacing: "0.1em" },
  pTitle: { fontFamily: FM, fontSize: 11, color: TX, letterSpacing: "0.2em", textTransform: "uppercase" },
  pHeadAct: { marginLeft: "auto", display: "flex", gap: 6, alignItems: "center" },
  miniBtn: { background: "transparent", border: "1px solid " + BD, color: TXM, padding: "3px 8px", fontFamily: FM, fontSize: 10, cursor: "pointer", borderRadius: 2 },
  cntBadge: { background: AC, color: BG, fontFamily: FM, fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 2 },
  field: { marginBottom: 12 },
  fieldRow: { display: "flex", gap: 12, marginBottom: 12 },
  fieldHalf: { flex: 1 },
  label: { display: "block", fontFamily: FM, fontSize: 10, color: TXD, textTransform: "uppercase", letterSpacing: "0.15em", marginBottom: 6 },
  select: { width: "100%", background: BG, border: "1px solid " + BDH, color: TX, padding: "10px 12px", fontFamily: FD, fontSize: 14, borderRadius: 2, boxSizing: "border-box" },
  input: { width: "100%", background: BG, border: "1px solid " + BDH, color: TX, padding: "10px 12px", fontFamily: FM, fontSize: 14, borderRadius: 2, boxSizing: "border-box" },
  readonly: { background: BG, border: "1px dashed " + BD, color: TXM, padding: "10px 12px", fontFamily: FM, fontSize: 14, borderRadius: 2 },
  meta: { display: "flex", gap: 8, flexWrap: "wrap" },
  chip: { fontFamily: FM, fontSize: 11, color: TXM, background: BG, border: "1px solid " + BD, padding: "4px 10px", borderRadius: 2 },
  chipHL: { fontFamily: FM, fontSize: 11, color: AC, background: "rgba(245,158,11,0.08)", border: "1px solid " + ACD, padding: "4px 10px", borderRadius: 2 },
  vanList: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 12 },
  vanRow: { display: "flex", alignItems: "center", gap: 12, padding: "8px 12px", background: BG, border: "1px solid " + BD, borderRadius: 2 },
  vanRowAct: { display: "flex", alignItems: "center", gap: 12, padding: "8px 12px", background: "rgba(245,158,11,0.06)", border: "1px solid " + ACD, borderRadius: 2 },
  vanLbl: { display: "flex", alignItems: "baseline", gap: 4, minWidth: 80 },
  vanCap: { fontFamily: FM, fontSize: 20, fontWeight: 700, color: TX },
  vanSuf: { fontFamily: FM, fontSize: 11, color: TXD },
  counter: { display: "flex", alignItems: "center", gap: 4 },
  cBtn: { width: 28, height: 28, background: BGD, border: "1px solid " + BDH, color: AC, fontSize: 16, fontWeight: 700, cursor: "pointer", borderRadius: 2, padding: 0, fontFamily: FM },
  cBtnD: { width: 28, height: 28, background: BGD, border: "1px solid " + BD, color: TXD, fontSize: 16, cursor: "not-allowed", borderRadius: 2, padding: 0, fontFamily: FM },
  cVal: { width: 32, textAlign: "center", fontFamily: FM, fontSize: 15, fontWeight: 700, color: TX },
  vanTot: { fontFamily: FM, fontSize: 11, color: AC, marginLeft: "auto" },
  capInfo: { display: "flex", alignItems: "center", gap: 12, padding: "10px 12px", background: BGD, border: "1px solid " + BD, borderRadius: 2 },
  capItem: { flex: 1 },
  capLbl: { display: "block", fontFamily: FM, fontSize: 9, color: TXD, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 2 },
  capVal: { fontFamily: FM, fontSize: 20, fontWeight: 700, color: TX },
  capValM: { fontFamily: FM, fontSize: 20, fontWeight: 700, color: TXD },
  capValOk: { fontFamily: FM, fontSize: 20, fontWeight: 700, color: GR },
  capValAl: { fontFamily: FM, fontSize: 20, fontWeight: 700, color: RD },
  capSep: { fontSize: 24, color: BDH, fontFamily: FM },
  textarea: { width: "100%", background: BG, border: "1px solid " + BDH, color: TX, padding: 12, fontFamily: FM, fontSize: 12, lineHeight: 1.6, borderRadius: 2, resize: "vertical", boxSizing: "border-box", minHeight: 100 },
  btnRow: { display: "flex", gap: 8, marginTop: 8 },
  btnSec: { flex: 1, background: "transparent", color: AC, border: "1px solid " + AC, padding: "10px 14px", fontFamily: FM, fontSize: 11, fontWeight: 700, letterSpacing: "0.15em", cursor: "pointer", borderRadius: 2 },
  btnSecD: { flex: 1, background: "transparent", color: TXD, border: "1px solid " + BD, padding: "10px 14px", fontFamily: FM, fontSize: 11, fontWeight: 700, letterSpacing: "0.15em", cursor: "not-allowed", borderRadius: 2 },
  listHead: { fontFamily: FM, fontSize: 10, color: TXD, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 6 },
  resList: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 8 },
  resRow: { display: "flex", alignItems: "center", gap: 6, background: BG, border: "1px solid " + BD, padding: "6px 8px", borderRadius: 2 },
  resNum: { fontFamily: FM, fontSize: 11, color: TXD, width: 20, textAlign: "center" },
  resEnd: { flex: 1, background: "transparent", border: "none", color: TX, padding: "6px 8px", fontFamily: FD, fontSize: 13, outline: "none", minWidth: 0 },
  resPax: { width: 44, background: BGD, border: "1px solid " + BDH, color: AC, padding: "6px 4px", fontFamily: FM, fontSize: 13, fontWeight: 700, borderRadius: 2, textAlign: "center", boxSizing: "border-box" },
  paxSuf: { fontFamily: FM, fontSize: 11, color: TXD, marginLeft: -2 },
  btnRem: { background: "transparent", color: RD, border: "1px solid " + BD, width: 26, height: 26, fontSize: 16, cursor: "pointer", borderRadius: 2, padding: 0 },
  btnAdd: { width: "100%", background: "transparent", color: AC, border: "1px dashed " + BDH, padding: 8, fontFamily: FM, fontSize: 10, cursor: "pointer", borderRadius: 2 },
  acts: { display: "flex", gap: 8 },
  btnPri: { flex: 1, background: AC, color: BG, border: "none", padding: "14px 20px", fontFamily: FM, fontSize: 12, fontWeight: 700, letterSpacing: "0.15em", cursor: "pointer", borderRadius: 2 },
  btnPriD: { flex: 1, background: BD, color: TXD, border: "none", padding: "14px 20px", fontFamily: FM, fontSize: 12, fontWeight: 700, letterSpacing: "0.15em", cursor: "not-allowed", borderRadius: 2 },
  btnGh: { background: "transparent", color: TXM, border: "1px solid " + BDH, padding: "14px 20px", fontFamily: FM, fontSize: 12, cursor: "pointer", borderRadius: 2 },
  btnGhF: { width: "100%", background: "transparent", color: AC, border: "1px dashed " + BDH, padding: 12, fontFamily: FM, fontSize: 11, cursor: "pointer", borderRadius: 2, marginTop: 8 },
  statusBox: { padding: 14, background: "rgba(59,130,246,0.08)", border: "1px solid #3b82f6", color: "#60a5fa", fontFamily: FM, fontSize: 12, borderRadius: 2 },
  empty: { textAlign: "center", padding: "60px 20px", color: TXD },
  emptyMark: { fontSize: 48, color: BDH, marginBottom: 16 },
  emptyHint: { fontSize: 12, color: TXD, marginTop: 8, fontFamily: FM, lineHeight: 1.8 },
  dragHint: { fontFamily: FM, fontSize: 10, color: TXD, textAlign: "center", marginBottom: 12, letterSpacing: "0.1em", textTransform: "uppercase" },
  rota: { background: BG, border: "1px solid " + BDH, borderRadius: 2, marginBottom: 12, overflow: "hidden" },
  rotaDrop: { background: "rgba(245,158,11,0.05)", border: "1px dashed " + AC, borderRadius: 2, marginBottom: 12, overflow: "hidden" },
  rotaHead: { display: "flex", alignItems: "center", gap: 12, padding: "10px 14px", background: "linear-gradient(90deg," + BGP + " 0%," + BG + " 100%)", borderBottom: "1px solid " + BD },
  rotaNum: { fontFamily: FM, fontSize: 11, color: AC, fontWeight: 700, letterSpacing: "0.15em" },
  rotaVan: { fontFamily: FM, fontSize: 13, color: TX, fontWeight: 600 },
  rotaPax: { fontFamily: FM, fontSize: 12, color: TXM, marginLeft: "auto" },
  rotaOcup: function (pct, exc) {
    var c = exc ? RD : pct >= 80 ? GR : pct >= 50 ? AC : TXM;
    return { fontFamily: FM, fontSize: 11, color: c, fontWeight: 700, padding: "2px 8px", border: "1px solid " + c, borderRadius: 2 };
  },
  paradas: { padding: 6 },
  parada: { display: "flex", alignItems: "center", gap: 10, padding: "8px 10px", borderBottom: "1px solid " + BD, cursor: "grab", userSelect: "none" },
  paradaDragTarget: { display: "flex", alignItems: "center", gap: 10, padding: "8px 10px", borderBottom: "1px solid " + AC, cursor: "grab", userSelect: "none", background: "rgba(245,158,11,0.04)" },
  pDrag: { color: BDH, fontFamily: FM, fontSize: 14, cursor: "grab", letterSpacing: "-2px" },
  pNum: { fontFamily: FM, fontSize: 13, fontWeight: 700, color: AC, width: 20, textAlign: "center" },
  pHora: { fontFamily: FM, fontSize: 13, fontWeight: 600, color: TX, minWidth: 48, background: BGD, padding: "4px 8px", border: "1px solid " + BD, borderRadius: 2, textAlign: "center" },
  pInfo: { flex: 1, minWidth: 0 },
  pEnd: { fontSize: 13, color: TX, fontFamily: FD },
  pMeta: { display: "flex", gap: 6, marginTop: 3, flexWrap: "wrap" },
  deslocCh: { fontFamily: FM, fontSize: 9, color: TXD, background: BD, padding: "1px 5px", borderRadius: 2 },
  comunaCh: { fontFamily: FM, fontSize: 9, color: TXM, padding: "1px 5px", borderRadius: 2 },
  unifCh: { fontFamily: FM, fontSize: 9, color: AC, padding: "1px 5px", borderRadius: 2 },
  errCh: { fontFamily: FM, fontSize: 9, color: RD, border: "1px solid " + RD, padding: "1px 5px", borderRadius: 2 },
  pRight: { display: "flex", alignItems: "center", gap: 6 },
  setorCh: function (s) {
    var c = TXD;
    if (s === 1) c = "#60a5fa"; if (s === 2) c = "#a78bfa";
    if (s === 3) c = "#34d399"; if (s === 4) c = AC;
    return { fontFamily: FM, fontSize: 10, color: c, border: "1px solid " + c, padding: "2px 6px", borderRadius: 2 };
  },
  paxBadge: { fontFamily: FM, fontSize: 11, color: TX, background: BD, padding: "2px 6px", borderRadius: 2, fontWeight: 600 },
  mapsLink: { display: "flex", alignItems: "center", justifyContent: "center", gap: 10, padding: "12px 14px", background: "rgba(59,130,246,0.08)", borderTop: "1px solid " + BD, color: "#60a5fa", fontFamily: FM, fontSize: 11, fontWeight: 700, letterSpacing: "0.15em", textDecoration: "none", cursor: "pointer" },
  cfgList: { display: "flex", flexDirection: "column", gap: 8 },
  cfgRow: { display: "flex", alignItems: "center", gap: 10 },
  cfgLbl: { fontFamily: FM, fontSize: 11, color: TXM, minWidth: 80, textTransform: "uppercase", letterSpacing: "0.1em" },
  cfgHint: { fontFamily: FM, fontSize: 11, color: TXD, marginBottom: 12, padding: "8px 12px", background: BGD, border: "1px solid " + BD, borderRadius: 2, lineHeight: 1.5 },
  inputN: { width: 60, background: BG, border: "1px solid " + BDH, color: AC, padding: "8px 10px", fontFamily: FM, fontSize: 13, fontWeight: 700, borderRadius: 2, textAlign: "center", boxSizing: "border-box" },
  inputT: { width: 90, background: BG, border: "1px solid " + BDH, color: AC, padding: "8px 10px", fontFamily: FM, fontSize: 13, borderRadius: 2, boxSizing: "border-box" },
  capLbl: { fontFamily: FM, fontSize: 11, color: TXD },
  tourNm: { flex: 2, fontSize: 13, color: TX, fontWeight: 500 },
  vetCh: { fontFamily: FM, fontSize: 10, color: TXM, background: BG, border: "1px solid " + BD, padding: "4px 8px", borderRadius: 2, width: 80, textAlign: "center", textTransform: "uppercase" },
  footer: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 32px", borderTop: "1px solid " + BD, fontFamily: FM, fontSize: 10, color: TXD, letterSpacing: "0.1em", textTransform: "uppercase" },
  fHint: { color: ACD }
};
